

service: sqstesttrigger

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        arn:aws:sqs:us-east-1:867061838226:demoqueue
functions:
  hello:
    handler: handler.hello
    reservedConcurrency: 10
    events:
      - sqs: 
        arn:
          arn:aws:sqs:us-east-1:867061838226:demoqueue
        batchSize: 1