service: sqstest
provider:
  name: aws
  stage: dev
  runtime: python3.6
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource: "arn:aws:sqs:us-east-1:*:demoqueue*"
  environment:
    sqs_url: <URL FILA PRINCIPAL>
    sqs_url_dest: <URL FILA DESTINO>
functions:
  sqsHandler:
    handler: lambda.handler
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: false