service: sqstest
provider:
  name: aws
  stage: dev
  runtime: python3.6
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource: "arn:aws:sqs:us-east-1:*:demoqueue*"
  environment:
    sqs_url: "https://sqs.us-east-1.amazonaws.com/799348652687/demoqueue"
    sqs_url_dest: "https://sqs.us-east-1.amazonaws.com/799348652687/demoqueue_dest"
functions:
  sqsHandler:
    handler: lambda.handler
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: false